services:
  mysql:
    image: mysql:8.0
    container_name: mysql-for-prisma
    env_file:
      - path: ./server/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
