-- 创建应用链接的 mysql 用户
CREATE USER IF NOT EXISTS MYSQL_USER@'%' IDENTIFIED BY MYSQL_PASSWORD;
GRANT ALL PRIVILEGES ON *.* TO 'MYSQL_USER'@'%';
GRANT CREATE, DROP ON *.* TO MYSQL_USER@'%';
FLUSH PRIVILEGES;
-- GRANT ALL PRIVILEGES ON MYSQL_DATABASE.* TO MYSQL_USER@'%';